const ERROR_ID_EMPTY = '아이디가 입력되지 않았습니다';
const ERROR_ID_VALIDATION = '잘못된 아이디입니다';
const ERROR_PASSWORD_EMPTY = '비밀번호가 입력되지 않았습니다';
const ERROR_PASSWORD_VALIDATION = '잘못된 비밀번호입니다.';
const ERROR_DIFFERENT_PASSWORD = '같은 비밀번호를 입력해주세요.';
const ERROR_CANNOT_RESERVATION = '이미 지난 날짜입니다.';
const ERROR_ID_DUPLICATION = '이미 사용중인 아이디 입니다.';
const ERROR_SUB_EMAIL_DUPLICATION = '이미 가입에 사용한 이메일 입니다.';
const ERROR_ID_AND_SUB_EMAIL_DUPLICATION = '이미 아이디와 이메일을 이미 사용하였습니다.';

export {
  ERROR_ID_EMPTY,
  ERROR_ID_VALIDATION,
  ERROR_PASSWORD_EMPTY,
  ERROR_PASSWORD_VALIDATION,
  ERROR_DIFFERENT_PASSWORD,
  ERROR_CANNOT_RESERVATION,
  ERROR_ID_DUPLICATION,
  ERROR_SUB_EMAIL_DUPLICATION,
  ERROR_ID_AND_SUB_EMAIL_DUPLICATION,
};
