module.exports = {
  DB_DEV_USERNAME: "",
  DB_DEV_PW: "",
  DB_DEV_SCHEMA: "",
  DB_DEV_HOST: "",
  STORAGE_END_POINT: "",
  STORAGE_REGION: "",
  STORAGE_BUCKET: "",
  STORAGE_ACCESS_KEY: "",
  STORAGE_SECRET_KEY: ""
};
