const SET_ID_ERROR_MSG = 'SET_ID_ERROR_MSG';
const SET_PASSWORD_ERROR_MSG = 'SET_PASSWORD_ERROR_MSG';
const SET_LOGIN_ERROR_MSG = 'SET_LOGIN_ERROR_MSG';
const RESET = 'RESET';

export { RESET, SET_ID_ERROR_MSG, SET_PASSWORD_ERROR_MSG, SET_LOGIN_ERROR_MSG };
